name: UtilityCommands
version: '${project.version}'
main: projects.utilitycommands.UtilityCommands
api-version: 1.18
commands:
  strike:
    description: hit a specified player with lightning
  boat:
    description: spawn a boat at the players location
  tphere:
    description: teleport a given player to ur location
  setbreak:
    description: enable or disable block breaking server wide

permissions:
  Util.strike:
    description: for being able to use the Strike command
    default: op
  Util.boat:
    description: for being able to use the Strike command
    default: op
  Util.tphere:
    description: for being able to use the tphere command
    default: op
  Util.setbreak:
    description: used to acces the setbreak command
    default: op
  Util.setbreak.bypass:
    description: used to BYPASS the nobreak function
    default: op