name: UtilityCommands
version: '${project.version}'
main: projects.utilitycommands.UtilityCommands
api-version: 1.18
commands:
  strike:
    description: hit a specified player with lightning
  boat:
    description: spawn a boat at the players location
  tphere:
    description: teleport a given player to ur location

permissions:
  Util.strike:
    description: for being able to use the Strike command
    default: op
  Util.boat:
    description: for being able to use the Strike command
    default: op
  Util.tphere:
    description: for being able to use the tphere command
    default: op
